sudo: false
language: node_js
node_js:
  - "14.10.1"
<<<<<<< HEAD
=======
cache:
  directories:
    - node_modules
services:
  - mongodb
>>>>>>> a47741d14a9ce897dd62b93e19f3bc70c4508279
branches:
  only:
    - CH-Tests
install:
  - npm install
  - npm install -g coveralls
cache:
  directories:
    - node_modules
script:
  - npm run test
after_success:
  - npm run coveralls

