sudo: false
language: node_js
node_js:
  - "14.10.1"
cache:
  directories:
    - node_modules
env: 
  - DB_URL = mongodb+srv://Elysee:Elysee@123@cluster0.03xpk.mongodb.net/mybrand?retryWrites=true&w=majority
  - DB_TEST_URL = mongodb+srv://user:user@cluster0.p4dy4.mongodb.net/testbrand?retryWrites=true&w=majority
  - JWT_SECRET_KEY = elysee
  - ADMIN_EMAIL = [nishimwelys@gmail.com,niyonshuti@gmail.com,elysee12345@gmail.com]
branches:
  only:
    - CH-Tests
install:
  - npm install
  - npm install -g coveralls
script:
  - npm run test
after_success:
  - npm run coveralls

