sudo: false
language: node_js
node_js:
  - "14.10.1"
branches:
  only:
    - CH-SwaggerDocumentation
install:
  - npm install
  - npm install -g coveralls
services:
  - mongodb
cache:
  directories:
    - node_modules
script:
  - npm run test
after_success:
  - npm run coveralls