sudo: false
language: node_js
node_js:
  - 14.10.1
cache:
  directories:
    - "node_modules"
branches:
  only:
    - CH-Tests
install:
  - npm install
  - npm install -g coveralls
script:
  - npm run test
after_success:
  - npm run coveralls
