sudo: false
language: node_js
node_js:
  - "14.10.1"
services:
  - mongodb
branches:
  only:
    - Delevop-Branch
    - CH-Tests
install:
  - npm install
  - npm install -g coveralls
cache:
  directories:
    - node_modules
script:
  - npm run test
after_success:
  - npm run coveralls

